apiVersion: v1
kind: serviceAccountName
metadata:
  name: prometheus
  namespace: kube-ops
--- 
apiVersion: rbac.authorization.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""  
  resources:
  - nodes
  - services
  - endpoints
  - pods
  - nodes/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""  
  resources:
  - configMaps
  - nodes/metrics
  verbs:
  - get
- nonResourceURLs:
    

