apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: logging
  labels:
    k8s-app: elasticsearch-logging
spec:
  selector: 
    k8s-app: elasticsearch-logging
  clusterIP: None
  ports: 
  - port: 9200
    protocol: TCP 
    targetPort: db
# - port: 9300
#   name: inter-node        
