apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-logging
  namespace: logging
  labels:
    k8s-app: elasticsearch-logging
spec:
  # serviceName: elasticsearch
  replicas: 1
  selector:
    k8s-app: elasticsearch-logging
  template:
    metadata:
      labels: 
        k8s-app: elasticsearch-logging
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.6.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 2400Mi
          requests:
            cpu: 100m
            memory: 2350Mi
        ports:
        - name: db
          containerPort: 9200
          protocol: TCP
        - name: transport
          containerPort: 9300
          protocol: TCP  
        volumeMounts:
        - name: elasticsearch
          mountPath: /usr/share/elasticsearch/data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: node.name
          value: es-0      
        - name: MINIMUM_MASTER_NODES
          value: "1"     
        - name: ES_JAVA_OPTS
          value: "-Xms1024m -Xmx1024m"
        - name: cluster.initial_master_nodes
          value: "es-0" 
      initContainers:
        - name: increase-vm-max-map
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true      
      volumes:
          - name: elasticsearch
            emptyDir: {}