apiVersion: v1
kind: Ingress
metadata:
  name: kibana
  namespace: logging
spec:
  rules:
  - host: kibana.leimeng.com
    http:  
      paths:
      - path: 
        backend:  
          serviceName: kibana-logging
          servicePort: 5601