apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-demo
spec:
  schedule: "*/1 * * * *" 
  successfulJobsHistoryLimit: 1 
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: hello
            image: busybox
            args:
            - "bin/sh" 
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1; do echo $i; done"